/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donatemanager;

import categorizemanager.CategorizeManager;
import displaymanager.DisplayManager;
import java.awt.Color;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author ircashem
 */
public class AddDonationUI extends javax.swing.JFrame {
    
    private DisplayManager mgr;
    private CategorizeManager cMgr;
    private DonationManager DM;
    
    /**
     * Creates new form AddNeed
     */
    public AddDonationUI(DisplayManager mgr, DonationManager DM, CategorizeManager cMgr) {
        
        this.mgr = mgr;
        this.DM = DM;
        this.cMgr = cMgr;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jTxtUserName = new javax.swing.JTextField();
        jTxtAddress = new javax.swing.JTextField();
        jTxtCategory = new javax.swing.JTextField();
        jTxtTop = new javax.swing.JTextField();
        jTxtBottom = new javax.swing.JTextField();
        jTxtWinter = new javax.swing.JTextField();
        jTxtFoot = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Add Donation");

        jLabel3.setText("Name");

        jLabel4.setText("Address");

        jLabel5.setText("Category(M/W/K)");

        jLabel6.setText("Top Wear Quantity");

        jLabel7.setText("Bottom Wear Quantity");

        jLabel8.setText("Winter Wear Quantity");

        jLabel9.setText("Foot Wear Quantity");

        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jButtonExit.setText("EXIT");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jTxtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtUserName.setMinimumSize(new java.awt.Dimension(5, 25));
        jTxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUserNameActionPerformed(evt);
            }
        });
        jTxtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtUserNameKeyReleased(evt);
            }
        });

        jTxtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtAddress.setMinimumSize(new java.awt.Dimension(5, 25));
        jTxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAddressActionPerformed(evt);
            }
        });
        jTxtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtAddressKeyReleased(evt);
            }
        });

        jTxtCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtCategory.setMinimumSize(new java.awt.Dimension(5, 25));
        jTxtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCategoryActionPerformed(evt);
            }
        });
        jTxtCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtCategoryKeyReleased(evt);
            }
        });

        jTxtTop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtTop.setMinimumSize(new java.awt.Dimension(5, 25));
        jTxtTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTopActionPerformed(evt);
            }
        });
        jTxtTop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtTopKeyReleased(evt);
            }
        });

        jTxtBottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtBottom.setMinimumSize(new java.awt.Dimension(5, 25));
        jTxtBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBottomActionPerformed(evt);
            }
        });
        jTxtBottom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtBottomKeyReleased(evt);
            }
        });

        jTxtWinter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtWinter.setMinimumSize(new java.awt.Dimension(5, 25));
        jTxtWinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtWinterActionPerformed(evt);
            }
        });
        jTxtWinter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtWinterKeyReleased(evt);
            }
        });

        jTxtFoot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtFoot.setMinimumSize(new java.awt.Dimension(5, 25));
        jTxtFoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFootActionPerformed(evt);
            }
        });
        jTxtFoot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtFootKeyReleased(evt);
            }
        });

        jButtonReset.setText("RESET");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(348, 348, 348)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonReset)
                                        .addGap(56, 56, 56)
                                        .addComponent(jButtonSubmit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(273, 273, 273)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTxtBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtWinter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtFoot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtTop, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 207, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jTxtTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jTxtBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jTxtWinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jTxtFoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmit)
                    .addComponent(jButtonReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButtonExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAddressActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
        // Complete
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        
     jTxtUserName.setText(null);
     jTxtAddress.setText(null);
     jTxtBottom.setText(null);
     jTxtCategory.setText(null);
     jTxtFoot.setText(null);
     jTxtTop.setText(null);
     jTxtUserName.setText(null);
     jTxtWinter.setText(null);
     
     jTxtUserName.setBackground(Color.white);
     jTxtAddress.setBackground(Color.white);
     jTxtCategory.setBackground(Color.white);
     jTxtTop.setBackground(Color.white);
     jTxtBottom.setBackground(Color.white);
     jTxtWinter.setBackground(Color.white);
     jTxtFoot.setBackground(Color.white);
        // Complete
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTxtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCategoryActionPerformed
//        String category = jTxtCategory.getText();
//        if (category.equals("M")){
//            jTxtCategory.setBackground(Color.green);
//        }
//        else{
//            jTxtCategory.setBackground(Color.red);
////            jTxtCategory.setBackground(Color.white);
//        }

        // TODO ad your handling code here:
    }//GEN-LAST:event_jTxtCategoryActionPerformed

    private void jTxtTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTopActionPerformed
//        String quantity = jTxtTop.getText();
//        int val = 0;
//        try {
//            val = Integer.parseInt(quantity);
//        }
//        catch (Exception e){
//            
//            jTxtTop.setBackground(Color.red);
//        }
//        if (val > 0){
//           jTxtTop.setBackground(Color.green);
//        }
//        else{
//            jTxtTop.setBackground(Color.red);
//        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTopActionPerformed

    private void jTxtBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBottomActionPerformed
//        String quantity = jTxtBottom.getText();
//        int val = 0;
//        try {
//            val = Integer.parseInt(quantity);
//        }
//        catch (Exception e){
//            
//            jTxtBottom.setBackground(Color.red);
//        }
//        if (val > 0){
//           jTxtBottom.setBackground(Color.green);
//        }
//        else{
//            jTxtBottom.setBackground(Color.red);
//        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBottomActionPerformed

    private void jTxtWinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtWinterActionPerformed
//        String quantity = jTxtWinter.getText();
//        int val = 0;
//        try {
//            val = Integer.parseInt(quantity);
//        }
//        catch (Exception e){
//            
//            jTxtWinter.setBackground(Color.red);
//        }
//        if (val > 0){
//           jTxtWinter.setBackground(Color.green);
//        }
//        else{
//            jTxtWinter.setBackground(Color.red);
//        }
//        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtWinterActionPerformed

    private void jTxtFootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFootActionPerformed
//        String quantity = jTxtFoot.getText();
//        int val = 0;
//        try {
//            val = Integer.parseInt(quantity);
//        }
//        catch (Exception e){
//            
//            jTxtFoot.setBackground(Color.red);
//        }
//        if (val > 0){
//           jTxtFoot.setBackground(Color.green);
//        }
//        else{
//            jTxtFoot.setBackground(Color.red);
//        }
//        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFootActionPerformed

    private void jTxtFootKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFootKeyReleased
        String quantity = jTxtFoot.getText();
        int val = -1;
        try {
            val = Integer.parseInt(quantity);
        }
        catch (Exception e){
            
            jTxtFoot.setBackground(Color.red);
        }
        if (val >= 0){
           jTxtFoot.setBackground(Color.green);
        }
        else{
            jTxtFoot.setBackground(Color.red);
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_jTxtFootKeyReleased

    private void jTxtWinterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtWinterKeyReleased
         String quantity = jTxtWinter.getText();
        int val = -1;
        try {
            val = Integer.parseInt(quantity);
        }
        catch (Exception e){
            
            jTxtWinter.setBackground(Color.red);
        }
        if (val >= 0){
           jTxtWinter.setBackground(Color.green);
        }
        else{
            jTxtWinter.setBackground(Color.red);
        }
              
        
// TODO add your handling code here:
    }//GEN-LAST:event_jTxtWinterKeyReleased

    private void jTxtBottomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBottomKeyReleased
         String quantity = jTxtBottom.getText();
        int val = -1;
        try {
            val = Integer.parseInt(quantity);
        }
        catch (Exception e){
            
            jTxtBottom.setBackground(Color.red);
        }
        if (val >= 0){
           jTxtBottom.setBackground(Color.green);
        }
        else{
            jTxtBottom.setBackground(Color.red);
        }


// TODO add your handling code here:
    }//GEN-LAST:event_jTxtBottomKeyReleased

    private void jTxtTopKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTopKeyReleased
         String quantity = jTxtTop.getText();
        int val = -1;
        try {
            val = Integer.parseInt(quantity);
        }
        catch (Exception e){
            
            jTxtTop.setBackground(Color.red);
        }
        if (val >= 0){
           jTxtTop.setBackground(Color.green);
        }
        else{
            jTxtTop.setBackground(Color.red);
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_jTxtTopKeyReleased

    private void jTxtCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCategoryKeyReleased
            String category = jTxtCategory.getText();
        if (category.equals("M") || category.equals("W") || category.equals("K")){
            jTxtCategory.setBackground(Color.green);
        }
        else{
            jTxtCategory.setBackground(Color.red);
//            jTxtCategory.setBackground(Color.white);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCategoryKeyReleased

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
            
        Donate d = new Donate();
        d.setName(jTxtUserName.getText());
        d.setAddress(jTxtAddress.getText());
        d.setCategory(jTxtCategory.getText());
        d.setTopWear(Integer.parseInt(jTxtTop.getText()));
        d.setBottomWear(Integer.parseInt(jTxtBottom.getText()));
        d.setWinterWear(Integer.parseInt(jTxtWinter.getText()));
        d.setFootWear(Integer.parseInt(jTxtFoot.getText()));

        if (this.DM.addDonate(d) == true){
            JOptionPane.showMessageDialog(null,"Successfully added your donation","Success",JOptionPane.INFORMATION_MESSAGE);
            this.cMgr.updateStockAfterAddingDonate(this.DM.getDonates());
            
            this.mgr.showManageDonationUI();
//            System.exit(0);
        }
        else{
            JOptionPane.showMessageDialog(null,"Error Occurred.","Error",JOptionPane.ERROR_MESSAGE);
//            System.exit(0);
        }
        
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jTxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUserNameActionPerformed

    private void jTxtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUserNameKeyReleased
        // Test Case 1 bug fixed here.
        String name = jTxtUserName.getText();
        if (name.equals("")){
            jTxtUserName.setBackground(Color.red);
        }
        else{
            jTxtUserName.setBackground(Color.green);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUserNameKeyReleased

    private void jTxtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtAddressKeyReleased
        // Test Case 1 bug fixed here.
        String name = jTxtAddress.getText();
        if (name.equals("")){
            jTxtAddress.setBackground(Color.red);
        }
        else{
            jTxtAddress.setBackground(Color.green);
        }
       
    }//GEN-LAST:event_jTxtAddressKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddNeedUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddNeedUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddNeedUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddNeedUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddNeedUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtBottom;
    private javax.swing.JTextField jTxtCategory;
    private javax.swing.JTextField jTxtFoot;
    private javax.swing.JTextField jTxtTop;
    private javax.swing.JTextField jTxtUserName;
    private javax.swing.JTextField jTxtWinter;
    // End of variables declaration//GEN-END:variables
}
